### ISSUE TITLE
Line Number Delimiter in Output Causes Terminal Links to Open in Browser

### ISSUE THREAD

**Issue by bflad** [katbyte/terrafmt#15]
Terminals such as iTerm2 will automatically create clickable links for patterns matching file paths and web URLs (to open, hover over while holding command key and click). The current output from `terrafmt` uses `#` as the delimiter between file names and line numbers, e.g.

```
aws/resource_aws_workspaces_directory_test.go#324
aws/resource_aws_workspaces_ip_group_test.go#127
aws/resource_aws_workspaces_ip_group_test.go#149
ERRO[0000] block 2 @ aws/resource_aws_xray_sampling_rule_test.go#194 failed to process with: failed to parse hcl: aws/resource_aws_xray_sampling_rule_test.go:3,20-21: Invalid expression; Expected the start of an expression, but found an invalid expression token.
```

When clicking those links they open in a web browser since presumably iTerm2 is treating them as a URL due to the `#` URL separator. Updating output to instead use `:` as a delimiter should allow terminals to treat these as file paths instead, so they open in your configured editor.

**Comment by katbyte** [comment]
🤯
