### ISSUE TITLE
Long lists always forced to one line?

### ISSUE THREAD

**Issue by YakDriver** [katbyte/terrafmt#34]
It seems like terrafmt prefers long one-liners over readable lists. It's after my own heart but perhaps less readable.

terrafmt is not happy with this but maybe _should_ be:
```hcl
resource "aws_docdb_cluster" "default" {
  availability_zones = [
    data.aws_availability_zones.available.names[0],
    data.aws_availability_zones.available.names[1],
    data.aws_availability_zones.available.names[2]
  ]
}
```

terrafmt is happy with this but maybe should _not_ be:
```hcl
resource "aws_docdb_cluster" "default" {
  availability_zones = [data.aws_availability_zones.available.names[0], data.aws_availability_zones.available.names[1], data.aws_availability_zones.available.names[2]]
}
```

**Comment by katbyte** [comment]
Hey @YakDriver - thanks for opening an issue but this would be related to how terraform itself formats tf files. I suggest opening an issue on https://github.com/hashicorp/terraform.
